### ISSUE TITLE
nagios creditales

### ISSUE THREAD

**Issue by EagleStrike42** [hudson-trading/netbox-nagios#11]
Seeing if it could be looked at adding an option to authenticate using credentals to Nagios in the future.

We're not seeing the connected host status intergrations inside Netbox (reporting NO DATA) and I believe it's related to our Nagios setup using LDAP auth through apache / htaccess. I've not been able to override it to accept LDAP OR access by the IP via htaccess, and it would simplify things if I could just provide our service account creds as part of the configuration.

Thanks

**Comment by sedyvlk** [comment]
This plugin uses nagios's [mklivestatus](https://docs.checkmk.com/latest/en/livestatus.html) to query host and services' status. AFAIK mklivestatus does not support auth. You problem is likely because there is a firewall blocking it or you do not have mklive status enabled. The plugin only uses the configured nagios url to provide links from netbox page.

**Comment by fabi125** [comment]
Yeah, what @sedyvlk said. This is just fetching data over a raw TCP connection. If you want to test it manually you can run:
```
$ nc <your nagios host> <mklivestatus port, usually 6557>
GET hosts
Filter: host_name = <some hostname>
OutputFormat: json
```
You might need to press enter twice before you get results back.
